---
# Ansible playbook for an ELK (Elasticsearch, Logstash, Kibana) logging server.
#
# @author Jeff Geerling (2014).

- hosts: logs
  gather_facts: yes

  vars_files:
    - vars/main.yml

  pre_tasks:
    - name: Update apt cache if needed.
      apt: update_cache=yes cache_valid_time=3600

  roles:
    - geerlingguy.java
    - geerlingguy.nginx
    - geerlingguy.elasticsearch
    - geerlingguy.kibana
    - geerlingguy.logstash
