---
# Ansible playbook for a LAMP server.
#
# @author Jeff Geerling (2014).

- hosts: lamp
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.mysql
    - geerlingguy.apache
    - geerlingguy.php
    - geerlingguy.php-mysql
